[package]
name = "pjccctl"
version = "0.1.0"
edition = "2023"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
reqwest = "0.11.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"