on:
  push:
    branches: 
      - main

permissions:
    contents: write
    packages: write

name: Test, Build and publish app release

jobs:
  test:
    name: run tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: ['1.20']
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - run: go test

  releases-matrix:
    name: Release Go Binary
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.20']
        goos: [linux]
        goarch: [amd64]
    steps:
    - uses: actions/checkout@v3
    - name: Generate release tag
      id: generate_release_tag
      uses: amitsingh-007/next-release-tag@v4.1.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag_prefix: ''
        tag_template: 'yyyy.mm.dd-i'

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.generate_release_tag.outputs.next_release_tag }}
        name: Release ${{ steps.generate_release_tag.outputs.next_release_tag }}

    - uses: wangyoucao577/go-release-action@v1
      with:
        release_tag: ${{ steps.generate_release_tag.outputs.next_release_tag }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: ${{ matrix.go-version }}
        binary_name: "pull-journal-central-client"
        # extra_files: LICENSE README.md
    
    - name: debian packaging
      run: mkdir -p build/packageroot/usr/bin
    - name: debian packaging
      run: cp -rf DEBIAN/* build/packageroot/   
    - name: debian packaging
      run: sed -i 's|%%VERSION%%|${{ steps.generate_release_tag.outputs.next_release_tag }}|g' build/packageroot/control
    - name: debian packaging
      run: cp pull-journal-central-client build/packageroot/usr/bin/
    - name: debian packaging
      run: cd build && dpkg-deb -b packageroot pull-journal-central-client_${{ steps.generate_release_tag.outputs.next_release_tag }}_amd64.deb
    - name: Release debian
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.generate_release_tag.outputs.next_release_tag }}
        name: Release ${{ steps.generate_release_tag.outputs.next_release_tag }}
        files: pull-journal-central-client_${{ steps.generate_release_tag.outputs.next_release_tag }}_amd64.deb
    

